# Generated by Django 4.1.1 on 2022-10-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('joining_date', models.DateTimeField(verbose_name='Joining date')),
                ('salary', models.IntegerField(verbose_name='salary')),
                ('role', models.CharField(max_length=200)),
                ('performance_persent', models.IntegerField(default=0)),
            ],
        ),
    ]
